// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace OpenMedStack.BioSharp.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "Equivalency")]
    public partial class ToolEquivalencyAcceptanceTestsFeature : object, Xunit.IClassFixture<ToolEquivalencyAcceptanceTestsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = new string[] {
                "Equivalency"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Tool Equivalency Acceptance Tests", "  As a bioinformatics developer\n  I want BioSharp to produce results equivalent t" +
                "o established external tools\n  So that clinical results can be independently val" +
                "idated and trusted", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "ToolEquivalency.feature"
#line hidden
        
        public ToolEquivalencyAcceptanceTestsFeature(ToolEquivalencyAcceptanceTestsFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ToolEquivalency.feature.ndjson", 28);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="BioSharp HashMap alignment produces equivalent mapped-read count to bwa mem")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tool Equivalency Acceptance Tests")]
        [global::Xunit.TraitAttribute("Description", "BioSharp HashMap alignment produces equivalent mapped-read count to bwa mem")]
        [global::Xunit.TraitAttribute("Category", "RequiresBwa")]
        [global::Xunit.TraitAttribute("Category", "RequiresSamtools")]
        [global::Xunit.InlineDataAttribute("10000", "100", "75", "10", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("50000", "200", "150", "10", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("10000", "300", "100", "10", "2", new string[0])]
        public async global::System.Threading.Tasks.Task BioSharpHashMapAlignmentProducesEquivalentMapped_ReadCountToBwaMem(string referenceSize, string readCount, string readLength, string tolerancePct, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RequiresBwa",
                    "RequiresSamtools"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ReferenceSize", referenceSize);
            argumentsOfScenario.Add("ReadCount", readCount);
            argumentsOfScenario.Add("ReadLength", readLength);
            argumentsOfScenario.Add("TolerancePct", tolerancePct);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BioSharp HashMap alignment produces equivalent mapped-read count to bwa mem", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync(string.Format("a synthetic FASTA reference of {0} bases seeded with random 42", referenceSize), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 16
    await testRunner.AndAsync(string.Format("{0} synthetic FASTQ reads of {1} bp derived from the reference with 10 percent SN" +
                            "P rate", readCount, readLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.WhenAsync("BioSharp aligns the reads using the HashMap seeder with seed size 11", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
    await testRunner.AndAsync("bwa mem aligns the same reads to the same reference", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.ThenAsync(string.Format("the BioSharp mapped count should be within {0} percent of the bwa mem mapped coun" +
                            "t", tolerancePct), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="BioSharp FmIndex alignment produces equivalent mapped-read count to bwa mem")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tool Equivalency Acceptance Tests")]
        [global::Xunit.TraitAttribute("Description", "BioSharp FmIndex alignment produces equivalent mapped-read count to bwa mem")]
        [global::Xunit.TraitAttribute("Category", "RequiresBwa")]
        [global::Xunit.TraitAttribute("Category", "RequiresSamtools")]
        [global::Xunit.InlineDataAttribute("10000", "100", "75", "10", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("50000", "200", "150", "10", "4", new string[0])]
        public async global::System.Threading.Tasks.Task BioSharpFmIndexAlignmentProducesEquivalentMapped_ReadCountToBwaMem(string referenceSize, string readCount, string readLength, string tolerancePct, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RequiresBwa",
                    "RequiresSamtools"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ReferenceSize", referenceSize);
            argumentsOfScenario.Add("ReadCount", readCount);
            argumentsOfScenario.Add("ReadLength", readLength);
            argumentsOfScenario.Add("TolerancePct", tolerancePct);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BioSharp FmIndex alignment produces equivalent mapped-read count to bwa mem", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
    await testRunner.GivenAsync(string.Format("a synthetic FASTA reference of {0} bases seeded with random 42", referenceSize), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.AndAsync(string.Format("{0} synthetic FASTQ reads of {1} bp derived from the reference with 10 percent SN" +
                            "P rate", readCount, readLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.WhenAsync("BioSharp aligns the reads using the FmIndex seeder", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
    await testRunner.AndAsync("bwa mem aligns the same reads to the same reference", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
    await testRunner.ThenAsync(string.Format("the BioSharp mapped count should be within {0} percent of the bwa mem mapped coun" +
                            "t", tolerancePct), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="BioSharp HashMap alignment produces equivalent mapped-read count to bwa-mem2")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tool Equivalency Acceptance Tests")]
        [global::Xunit.TraitAttribute("Description", "BioSharp HashMap alignment produces equivalent mapped-read count to bwa-mem2")]
        [global::Xunit.TraitAttribute("Category", "RequiresBwaMem2")]
        [global::Xunit.InlineDataAttribute("10000", "100", "75", "10", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("50000", "200", "150", "10", "6", new string[0])]
        public async global::System.Threading.Tasks.Task BioSharpHashMapAlignmentProducesEquivalentMapped_ReadCountToBwa_Mem2(string referenceSize, string readCount, string readLength, string tolerancePct, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RequiresBwaMem2"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ReferenceSize", referenceSize);
            argumentsOfScenario.Add("ReadCount", readCount);
            argumentsOfScenario.Add("ReadLength", readLength);
            argumentsOfScenario.Add("TolerancePct", tolerancePct);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BioSharp HashMap alignment produces equivalent mapped-read count to bwa-mem2", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 54
    await testRunner.GivenAsync(string.Format("a synthetic FASTA reference of {0} bases seeded with random 42", referenceSize), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
    await testRunner.AndAsync(string.Format("{0} synthetic FASTQ reads of {1} bp derived from the reference with 10 percent SN" +
                            "P rate", readCount, readLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
    await testRunner.WhenAsync("BioSharp aligns the reads using the HashMap seeder with seed size 11", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.AndAsync("bwa-mem2 aligns the same reads to the same reference", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
    await testRunner.ThenAsync(string.Format("the BioSharp mapped count should be within {0} percent of the bwa-mem2 mapped cou" +
                            "nt", tolerancePct), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="BioSharp adapter trimming produces equivalent surviving read count to fastp")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tool Equivalency Acceptance Tests")]
        [global::Xunit.TraitAttribute("Description", "BioSharp adapter trimming produces equivalent surviving read count to fastp")]
        [global::Xunit.TraitAttribute("Category", "RequiresFastp")]
        [global::Xunit.InlineDataAttribute("1000", "100", "30", "\"AGATCGGAAGAGCACACGTCTGAACTCCAGTCA\"", "20", "10", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("1000", "100", "60", "\"CTGTCTCTTATACACATCT\"", "20", "10", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("500", "150", "50", "\"AGATCGGAAGAGCACACGTCTGAACTCCAGTCA\"", "50", "10", "9", new string[0])]
        public async global::System.Threading.Tasks.Task BioSharpAdapterTrimmingProducesEquivalentSurvivingReadCountToFastp(string readCount, string readLength, string adapterFraction, string adapter, string minLength, string tolerancePct, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RequiresFastp"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ReadCount", readCount);
            argumentsOfScenario.Add("ReadLength", readLength);
            argumentsOfScenario.Add("AdapterFraction", adapterFraction);
            argumentsOfScenario.Add("Adapter", adapter);
            argumentsOfScenario.Add("MinLength", minLength);
            argumentsOfScenario.Add("TolerancePct", tolerancePct);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BioSharp adapter trimming produces equivalent surviving read count to fastp", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 72
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 73
    await testRunner.GivenAsync(string.Format("{0} FASTQ reads of {1} bp with {2} percent carrying adapter {3}", readCount, readLength, adapterFraction, adapter), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 74
    await testRunner.WhenAsync(string.Format("BioSharp trims adapter {0} with minimum length {1} and max mismatches 2", adapter, minLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 75
    await testRunner.AndAsync(string.Format("fastp trims the reads with adapter {0} and minimum length {1}", adapter, minLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
    await testRunner.ThenAsync(string.Format("the BioSharp surviving read count should be within {0} percent of the fastp survi" +
                            "ving count", tolerancePct), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="BioSharp bases removed by adapter trimming is within tolerance of fastp")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tool Equivalency Acceptance Tests")]
        [global::Xunit.TraitAttribute("Description", "BioSharp bases removed by adapter trimming is within tolerance of fastp")]
        [global::Xunit.TraitAttribute("Category", "RequiresFastp")]
        [global::Xunit.InlineDataAttribute("1000", "100", "30", "\"AGATCGGAAGAGCACACGTCTGAACTCCAGTCA\"", "20", "15", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("1000", "100", "60", "\"CTGTCTCTTATACACATCT\"", "20", "15", "11", new string[0])]
        public async global::System.Threading.Tasks.Task BioSharpBasesRemovedByAdapterTrimmingIsWithinToleranceOfFastp(string readCount, string readLength, string adapterFraction, string adapter, string minLength, string tolerancePct, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RequiresFastp"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ReadCount", readCount);
            argumentsOfScenario.Add("ReadLength", readLength);
            argumentsOfScenario.Add("AdapterFraction", adapterFraction);
            argumentsOfScenario.Add("Adapter", adapter);
            argumentsOfScenario.Add("MinLength", minLength);
            argumentsOfScenario.Add("TolerancePct", tolerancePct);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BioSharp bases removed by adapter trimming is within tolerance of fastp", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 92
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 93
    await testRunner.GivenAsync(string.Format("{0} FASTQ reads of {1} bp with {2} percent carrying adapter {3}", readCount, readLength, adapterFraction, adapter), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 94
    await testRunner.WhenAsync(string.Format("BioSharp trims adapter {0} with minimum length {1} and max mismatches 2", adapter, minLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 95
    await testRunner.AndAsync(string.Format("fastp trims the reads with adapter {0} and minimum length {1}", adapter, minLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
    await testRunner.ThenAsync(string.Format("the BioSharp bases removed should be within {0} percent of the fastp bases remove" +
                            "d", tolerancePct), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="BioSharp adapter trimming produces equivalent surviving read count to cutadapt")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tool Equivalency Acceptance Tests")]
        [global::Xunit.TraitAttribute("Description", "BioSharp adapter trimming produces equivalent surviving read count to cutadapt")]
        [global::Xunit.TraitAttribute("Category", "RequiresCutadapt")]
        [global::Xunit.InlineDataAttribute("1000", "100", "30", "\"AGATCGGAAGAGCACACGTCTGAACTCCAGTCA\"", "20", "10", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("1000", "100", "60", "\"CTGTCTCTTATACACATCT\"", "20", "10", "13", new string[0])]
        [global::Xunit.InlineDataAttribute("500", "150", "50", "\"AGATCGGAAGAGCACACGTCTGAACTCCAGTCA\"", "50", "10", "14", new string[0])]
        public async global::System.Threading.Tasks.Task BioSharpAdapterTrimmingProducesEquivalentSurvivingReadCountToCutadapt(string readCount, string readLength, string adapterFraction, string adapter, string minLength, string tolerancePct, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RequiresCutadapt"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ReadCount", readCount);
            argumentsOfScenario.Add("ReadLength", readLength);
            argumentsOfScenario.Add("AdapterFraction", adapterFraction);
            argumentsOfScenario.Add("Adapter", adapter);
            argumentsOfScenario.Add("MinLength", minLength);
            argumentsOfScenario.Add("TolerancePct", tolerancePct);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BioSharp adapter trimming produces equivalent surviving read count to cutadapt", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 110
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 111
    await testRunner.GivenAsync(string.Format("{0} FASTQ reads of {1} bp with {2} percent carrying adapter {3}", readCount, readLength, adapterFraction, adapter), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 112
    await testRunner.WhenAsync(string.Format("BioSharp trims adapter {0} with minimum length {1} and max mismatches 2", adapter, minLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 113
    await testRunner.AndAsync(string.Format("cutadapt trims the reads with adapter {0} and minimum length {1}", adapter, minLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
    await testRunner.ThenAsync(string.Format("the BioSharp surviving read count should be within {0} percent of the cutadapt su" +
                            "rviving count", tolerancePct), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="BioSharp bases removed by adapter trimming is within tolerance of cutadapt")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tool Equivalency Acceptance Tests")]
        [global::Xunit.TraitAttribute("Description", "BioSharp bases removed by adapter trimming is within tolerance of cutadapt")]
        [global::Xunit.TraitAttribute("Category", "RequiresCutadapt")]
        [global::Xunit.InlineDataAttribute("1000", "100", "30", "\"AGATCGGAAGAGCACACGTCTGAACTCCAGTCA\"", "20", "15", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("1000", "100", "60", "\"CTGTCTCTTATACACATCT\"", "20", "15", "16", new string[0])]
        public async global::System.Threading.Tasks.Task BioSharpBasesRemovedByAdapterTrimmingIsWithinToleranceOfCutadapt(string readCount, string readLength, string adapterFraction, string adapter, string minLength, string tolerancePct, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RequiresCutadapt"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ReadCount", readCount);
            argumentsOfScenario.Add("ReadLength", readLength);
            argumentsOfScenario.Add("AdapterFraction", adapterFraction);
            argumentsOfScenario.Add("Adapter", adapter);
            argumentsOfScenario.Add("MinLength", minLength);
            argumentsOfScenario.Add("TolerancePct", tolerancePct);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BioSharp bases removed by adapter trimming is within tolerance of cutadapt", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 127
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 128
    await testRunner.GivenAsync(string.Format("{0} FASTQ reads of {1} bp with {2} percent carrying adapter {3}", readCount, readLength, adapterFraction, adapter), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 129
    await testRunner.WhenAsync(string.Format("BioSharp trims adapter {0} with minimum length {1} and max mismatches 2", adapter, minLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 130
    await testRunner.AndAsync(string.Format("cutadapt trims the reads with adapter {0} and minimum length {1}", adapter, minLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 131
    await testRunner.ThenAsync(string.Format("the BioSharp bases removed should be within {0} percent of the cutadapt bases rem" +
                            "oved", tolerancePct), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="BioSharp total read count matches fastqc exactly")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tool Equivalency Acceptance Tests")]
        [global::Xunit.TraitAttribute("Description", "BioSharp total read count matches fastqc exactly")]
        [global::Xunit.TraitAttribute("Category", "RequiresFastqc")]
        [global::Xunit.InlineDataAttribute("1000", "75", "30", "17", new string[0])]
        [global::Xunit.InlineDataAttribute("500", "150", "20", "18", new string[0])]
        [global::Xunit.InlineDataAttribute("200", "100", "40", "19", new string[0])]
        public async global::System.Threading.Tasks.Task BioSharpTotalReadCountMatchesFastqcExactly(string readCount, string readLength, string qualScore, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RequiresFastqc"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ReadCount", readCount);
            argumentsOfScenario.Add("ReadLength", readLength);
            argumentsOfScenario.Add("QualScore", qualScore);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BioSharp total read count matches fastqc exactly", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 145
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 146
    await testRunner.GivenAsync(string.Format("{0} uniform-quality FASTQ reads of {1} bp with quality score {2}", readCount, readLength, qualScore), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 147
    await testRunner.WhenAsync("BioSharp computes the FastQ quality report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 148
    await testRunner.AndAsync("fastqc analyses the same FASTQ reads", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 149
    await testRunner.ThenAsync("the BioSharp total read count should match the fastqc total read count exactly", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="BioSharp mean per-base quality is within tolerance of fastqc")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tool Equivalency Acceptance Tests")]
        [global::Xunit.TraitAttribute("Description", "BioSharp mean per-base quality is within tolerance of fastqc")]
        [global::Xunit.TraitAttribute("Category", "RequiresFastqc")]
        [global::Xunit.InlineDataAttribute("1000", "75", "30", "5", "20", new string[0])]
        [global::Xunit.InlineDataAttribute("1000", "150", "20", "5", "21", new string[0])]
        public async global::System.Threading.Tasks.Task BioSharpMeanPer_BaseQualityIsWithinToleranceOfFastqc(string readCount, string readLength, string qualScore, string tolerancePct, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RequiresFastqc"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ReadCount", readCount);
            argumentsOfScenario.Add("ReadLength", readLength);
            argumentsOfScenario.Add("QualScore", qualScore);
            argumentsOfScenario.Add("TolerancePct", tolerancePct);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BioSharp mean per-base quality is within tolerance of fastqc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 164
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 165
    await testRunner.GivenAsync(string.Format("{0} uniform-quality FASTQ reads of {1} bp with quality score {2}", readCount, readLength, qualScore), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 166
    await testRunner.WhenAsync("BioSharp computes the FastQ quality report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 167
    await testRunner.AndAsync("fastqc analyses the same FASTQ reads", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 168
    await testRunner.ThenAsync(string.Format("the BioSharp mean per-base quality should be within {0} percent of the fastqc mea" +
                            "n quality", tolerancePct), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="BioSharp SNP calls overlap with freebayes calls")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tool Equivalency Acceptance Tests")]
        [global::Xunit.TraitAttribute("Description", "BioSharp SNP calls overlap with freebayes calls")]
        [global::Xunit.TraitAttribute("Category", "RequiresBwa")]
        [global::Xunit.TraitAttribute("Category", "RequiresSamtools")]
        [global::Xunit.TraitAttribute("Category", "RequiresFreebayes")]
        [global::Xunit.InlineDataAttribute("10000", "5", "500", "150", "50", "22", new string[0])]
        [global::Xunit.InlineDataAttribute("10000", "10", "1000", "150", "50", "23", new string[0])]
        public async global::System.Threading.Tasks.Task BioSharpSNPCallsOverlapWithFreebayesCalls(string referenceSize, string snpCount, string readCount, string readLength, string minOverlapPct, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RequiresBwa",
                    "RequiresSamtools",
                    "RequiresFreebayes"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ReferenceSize", referenceSize);
            argumentsOfScenario.Add("SnpCount", snpCount);
            argumentsOfScenario.Add("ReadCount", readCount);
            argumentsOfScenario.Add("ReadLength", readLength);
            argumentsOfScenario.Add("MinOverlapPct", minOverlapPct);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BioSharp SNP calls overlap with freebayes calls", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 184
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 185
    await testRunner.GivenAsync(string.Format("a synthetic FASTA reference of {0} bases with {1} planted SNPs seeded with random" +
                            " 42", referenceSize, snpCount), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 186
    await testRunner.AndAsync(string.Format("{0} FASTQ reads of {1} bp covering those SNP positions", readCount, readLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 187
    await testRunner.WhenAsync("a sorted BAM is produced by aligning the reads with bwa mem and sorting with samt" +
                        "ools", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 188
    await testRunner.AndAsync("BioSharp calls variants from that BAM using the HashMap seeder", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 189
    await testRunner.AndAsync("freebayes calls variants from the same BAM", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 190
    await testRunner.ThenAsync(string.Format("the BioSharp SNP positions should overlap freebayes SNP positions by at least {0}" +
                            " percent", minOverlapPct), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="BioSharp SNP calls overlap with samtools mpileup bcftools call")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tool Equivalency Acceptance Tests")]
        [global::Xunit.TraitAttribute("Description", "BioSharp SNP calls overlap with samtools mpileup bcftools call")]
        [global::Xunit.TraitAttribute("Category", "RequiresBwa")]
        [global::Xunit.TraitAttribute("Category", "RequiresSamtools")]
        [global::Xunit.TraitAttribute("Category", "RequiresBcftools")]
        [global::Xunit.InlineDataAttribute("10000", "5", "500", "150", "50", "24", new string[0])]
        [global::Xunit.InlineDataAttribute("10000", "10", "1000", "150", "50", "25", new string[0])]
        public async global::System.Threading.Tasks.Task BioSharpSNPCallsOverlapWithSamtoolsMpileupBcftoolsCall(string referenceSize, string snpCount, string readCount, string readLength, string minOverlapPct, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RequiresBwa",
                    "RequiresSamtools",
                    "RequiresBcftools"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ReferenceSize", referenceSize);
            argumentsOfScenario.Add("SnpCount", snpCount);
            argumentsOfScenario.Add("ReadCount", readCount);
            argumentsOfScenario.Add("ReadLength", readLength);
            argumentsOfScenario.Add("MinOverlapPct", minOverlapPct);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BioSharp SNP calls overlap with samtools mpileup bcftools call", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 204
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 205
    await testRunner.GivenAsync(string.Format("a synthetic FASTA reference of {0} bases with {1} planted SNPs seeded with random" +
                            " 42", referenceSize, snpCount), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 206
    await testRunner.AndAsync(string.Format("{0} FASTQ reads of {1} bp covering those SNP positions", readCount, readLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 207
    await testRunner.WhenAsync("a sorted BAM is produced by aligning the reads with bwa mem and sorting with samt" +
                        "ools", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 208
    await testRunner.AndAsync("BioSharp calls variants from that BAM using the HashMap seeder", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 209
    await testRunner.AndAsync("samtools mpileup piped to bcftools calls variants from the same BAM", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 210
    await testRunner.ThenAsync(string.Format("the BioSharp SNP positions should overlap samtools-bcftools SNP positions by at l" +
                            "east {0} percent", minOverlapPct), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ToolEquivalencyAcceptanceTestsFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await ToolEquivalencyAcceptanceTestsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
